keystone:
    image: 'keystone_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    environment:
        - MYSQL_IP=10.229.43.217
        - CONTROLLER=10.229.43.217
        - OS_TOKEN=016f77abde58da9c724b
        - OS_IDENTITY_API_VERSION=3
        - OS_URL=http://10.229.43.217:35357/v3
        - KEYSTONE_DBPASS=redhat
        - ADMIN_TOKEN=016f77abde58da9c724b
        - ADMIN_PASS=redhat
        - DEMO_PASS=redhat
        - CEILOMETER_PASS=redhat
        - GLANCE_PASS=redhat

mariadb:
    image: "mariadb_test:1"
    net: "host"
    #expose:
    #    - "3306"
    environment:
        - INIT_DB=True
        - BIND_ADDRESS=10.229.43.217
        - MYSQL_ROOT_PASSWORD=redhat
        - DB_PASS=redhat
        - KEYSTONE_DBPASS=redhat
        - GLANCE_DBPASS=redhat
        - NOVA_DBPASS=redhat
        - NEUTRON_DBPASS=redhat
        - CINDER_DBPASS=redhat
        - MANILA_DBPASS=redhat
        - HEAT_DBPASS=redhat
        - TROVE_DBPASS=redhat

mongodb:
    image: 'mongodb_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    volumes:
        - /home/zsz/mongodb/mongod.conf:/etc/mongod.conf

ceilometer_api:
    image: 'ceilometer_api_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    volumes:
        - /home/zsz/ceilometer-api/ceilometer.conf:/etc/ceilometer/ceilometer.conf

ceilometer_central:
    image: 'ceilometer_central_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    volumes:
        - /home/zsz/ceilometer-central/ceilometer.conf:/etc/ceilometer/ceilometer.conf

ceilometer_collector:
    image: 'ceilometer_collector_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    volumes:
        - /home/zsz/ceilometer-collector/ceilometer.conf:/etc/ceilometer/ceilometer.conf

ceilometer_notification:
    image: 'ceilometer_notification_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    volumes:
        - /home/zsz/ceilometer-notification/ceilometer.conf:/etc/ceilometer/ceilometer.conf





















