FROM centos:7

ADD ./CentOS7-Base-163.repo /etc/yum.repos.d/CentOS-Base.repo
ADD ./config.sh /home/config.sh
ADD ./env.sh /home/env.sh
ADD ./keystone_install.sh /home/keystone_install.sh
ADD ./keystone_setup.sh /home/keystone_setup.sh
ADD ./os-openrc.sh /home/os-openrc.sh

RUN yum clean all
RUN yum makecache

RUN yum install -y openstack-keystone openstack-utils