version: '2'
services:
  mariadb:
    image: 'mariadb:latest'
    network_mode: "host"
    environment:
        - MYSQL_ROOT_PASSWORD=redhat

  mariadbinit:
    image: 'mariadbinit:latest'
    #ports:
    #    - "8880:80"
    links:
        - mariadb
    environment:
        - MARIADB_INIT=True
        - MYSQL_IP=10.229.43.217
        - DB_PASS=redhat
        - KEYSTONE_DBPASS=redhat
        - GLANCE_DBPASS=redhat
        - NOVA_DBPASS=redhat
        - NEUTRON_DBPASS=redhat
        - CINDER_DBPASS=redhat
        - MANILA_DBPASS=redhat
        - HEAT_DBPASS=redhat
        - TROVE_DBPASS=redhat

  keystone:
    image: 'keystone_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    environment:
        - KEYSTONE_INIT=True
        - MYSQL_IP=10.229.43.217
        - CONTROLLER=10.229.43.217
        - KEYSTONE_DBPASS=redhat
        - ADMIN_TOKEN=016f77abde58da9c724b
        - ADMIN_PASS=redhat
        - DEMO_PASS=redhat
        - CEILOMETER_PASS=redhat
        - GLANCE_PASS=redhat

  mongodb:
    image: 'mongodb_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/mongodb/mongod.conf:/etc/mongod.conf

  ceilometer_api:
    image: 'ceilometer_api_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-api/ceilometer.conf:/etc/ceilometer/ceilometer.conf

  ceilometer_central:
    image: 'ceilometer_central_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-central/ceilometer.conf:/etc/ceilometer/ceilometer.conf

  ceilometer_collector:
    image: 'ceilometer_collector_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-collector/ceilometer.conf:/etc/ceilometer/ceilometer.conf

  ceilometer_notification:
    image: 'ceilometer_notification_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-notification/ceilometer.conf:/etc/ceilometer/ceilometer.conf





















