version: '2'
services:
  mariadb:
    image: 'mariadb:latest'
    network_mode: "host"
    environment:
        - MYSQL_ROOT_PASSWORD=redhat

  mariadb_init:
    image: 'mariadb_init:latest'
    #ports:
    #    - "8880:80"
    links:
        - mariadb
    environment:
        - DB_HOST=10.229.43.217
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASS=redhat
        - KEYSTONE_DB_PASS=redhat
        - GLANCE_DB_PASS=redhat
        - NOVA_DB_PASS=redhat
        - NEUTRON_DB_PASS=redhat
        - CINDER_DB_PASS=redhat

  keystone:
    image: 'keystone:1'
    network_mode: "host"
    environment:
        - ADMIN_TOKEN=016f77abde58da9c724b
        - KEYSTONE_DB_PASS=redhat
        - DB_HOST=10.229.43.217
        - KEYSTONE_INIT=True
        - CONTROLLER=10.229.43.217
        - ADMIN_PASS=redhat
        - DEMO_PASS=redhat
  keystone_init:
    image: 'keystone_init:1'
    links:
        - keystone
    environment:
        - ADMIN_TOKEN=016f77abde58da9c724b
        - CONTROLLER=10.229.43.217
        - ADMIN_PASS=redhat
        - DEMO_PASS=redhat
        - CEILOMETER_PASS=redhat
        - GLANCE_PASS=redhat

  mongodb:
    image: 'mongodb_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/mongodb/mongod.conf:/etc/mongod.conf

  ceilometer_api:
    image: 'ceilometer_api_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-api/ceilometer.conf:/etc/ceilometer/ceilometer.conf

  ceilometer_central:
    image: 'ceilometer_central_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-central/ceilometer.conf:/etc/ceilometer/ceilometer.conf

  ceilometer_collector:
    image: 'ceilometer_collector_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-collector/ceilometer.conf:/etc/ceilometer/ceilometer.conf

  ceilometer_notification:
    image: 'ceilometer_notification_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    network_mode: "host"
    volumes:
        - /home/openstack-install/ceilometer-notification/ceilometer.conf:/etc/ceilometer/ceilometer.conf





















