#!/bin/bash

DEFAULT_PASS=redhat
ADMIN_PASS=$DEFAULT_PASS
DEMO_PASS=$DEFAULT_PASS

DB_PASS=$DEFAULT_PASS

RABBIT_PASS=$DEFAULT_PASS

KEYSTONE_DBPASS=$DEFAULT_PASS

GLANCE_PASS=$DEFAULT_PASS
GLANCE_DBPASS=$DEFAULT_PASS
