#!/bin/bash

DEFAULT_PASS=redhat
ADMIN_PASS=$DEFAULT_PASS
DEMO_PASS=$DEFAULT_PASS

DB_PASS=$DEFAULT_PASS

RABBIT_PASS=$DEFAULT_PASS

KEYSTONE_DBPASS=$DEFAULT_PASS

GLANCE_PASS=$DEFAULT_PASS
GLANCE_DBPASS=$DEFAULT_PASS

NOVA_PASS=$DEFAULT_PASS
NOVA_DBPASS=$DEFAULT_PASS

NEUTRON_PASS=$DEFAULT_PASS
NEUTRON_DBPASS=$DEFAULT_PASS

METADATA_SECRET=$DEFAULT_PASS
PROVIDER_IFCE_NAME=eth0
