version: '2'
services:
  etcd:
    image: 'quay.io/coreos/etcd:v2.2.5'
    network_mode: "bridge"
    ports:
        - "PEER_PORT:2380"
        - "CLIENT_PORT:2379"
    environment:
        - ETCD_NAME=NAME_VAR
        - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://ADVERTISEMENT_HOST:PEER_PORT
        - ETCD_LISTEN_PEER_URLS=http://ADVERTISEMENT_HOST:PEER_PORT
        - ETCD_ADVERTISE_CLIENT_URLS=http://ADVERTISEMENT_HOST:CLIENT_PORT
        - ETCD_LISTEN_CLIENT_URLS=http://ADVERTISEMENT_HOST:CLIENT_PORT
        - ETCD_INITIAL_CLUSTER=NAME_VAR=http://ADVERTISEMENT_HOST:PEER_PORT
        - ETCD_INITIAL_CLUSTER_STATE=STATE_VAR
        - ETCD_INITIAL_CLUSTER_TOKEN=TOKEN_VAR
