keystone:
    image: 'keystone_test:1'
    #ports:
    #    - "8880:80"
    #links:
    #    - mysql
    net: "host"
    environment:
        - KEYSTONE_INIT=True
        - MYSQL_IP=10.229.43.217
        - CONTROLLER=10.229.43.217
        - KEYSTONE_DBPASS=redhat
        - ADMIN_TOKEN=016f77abde58da9c724b
        - ADMIN_PASS=redhat
        - DEMO_PASS=redhat
        - CEILOMETER_PASS=redhat
        - GLANCE_PASS=redhat
