version: '2'
services:
   keystone:
     image: 'keystone:1'
     network_mode: "bridge"
     ports:
         - "KEYSTONE_ADMIN_PORT:35357"
         - "KEYSTONE_INTERNAL_PORT:5000"
     environment:
         - ADMIN_TOKEN=ADMIN_TOKEN_VAR
         - KEYSTONE_DB_PASS=KEYSTONE_DB_PASS_VAR
         - DB_HOST=DB_HOST_VAR
         - DB_PORT=DB_PORT_VAR
         - DB_USER=DB_USER_VAR
         - DB_PASS=DB_PASS_VAR
