mariadb:
    image: "mariadb_test:1"
    net: "host"
    #expose:
    #    - "3306"
    environment:
        - INIT_DB=True
        - BIND_ADDRESS=10.229.43.217
        - MYSQL_ROOT_PASSWORD=redhat
        - DB_PASS=redhat
        - KEYSTONE_DBPASS=redhat
        - GLANCE_DBPASS=redhat
        - NOVA_DBPASS=redhat
        - NEUTRON_DBPASS=redhat
        - CINDER_DBPASS=redhat
        - MANILA_DBPASS=redhat
        - HEAT_DBPASS=redhat
        - TROVE_DBPASS=redhat

